apiVersion: v2
name: stp-o11y
description: A Helm chart for stp-o11y tools
type: application
version: 0.1.2
appVersion: "0.0.0"
dependencies:
  - name: kubernetes-event-exporter
    version: 2.10.1
    repository: "https://charts.bitnami.com/bitnami"
    condition: kubernetes-event-exporter.enabled
