apiVersion: v2
name: stp-o11y
description: A Helm chart for stp-o11y tools
type: application
version: 0.1.1
appVersion: "0.0.0"
dependencies:
  - name: kubernetes-event-exporter
    version: 2.10.0
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: kubernetes-event-exporter.enabled
