{{- if .Values.mtail.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mtail
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: mtail
  template:
    metadata:
      labels:
        app: mtail
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/mtail/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: mtail
        image: "{{ .Values.mtail.image.repository }}:{{ .Values.mtail.image.tag }}"
        args: 
        - -progs
        - /etc/mtail
        - -port
        - "3903"
        {{- range .Values.containerLogs }}
        - "-logs"
        - "/var/log/containers/{{ . }}"
        {{- end }}
        ports:
        - containerPort: 3903
          name: metrics
        resources:
          {{- toYaml .Values.mtail.resources | nindent 10 }}
        volumeMounts:
        - name: mtail-config
          mountPath: /etc/mtail
      volumes:
      - name: mtail-config
        configMap:
          name: mtail-config
{{- end }}