receivers:
  otlp/ecs-otel:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus/ecs:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
          - targets:
              - ${env:HOSTNAME}:8888

exporters:
  debug:
    verbosity: detailed
  otlphttp/cent-monitor:
    endpoint: ${otlp_exporter_endpoint_cent}
  otlphttp/tperd-monitor:
    endpoint: ${otlp_exporter_endpoint_tperd}

processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
      - key: "splashtop.env"
        value: ${splashtop_env}
        action: "insert"
      - key: "splashtop.stack"
        value: ${splashtop_stack}
        action: "insert"
  # add attribute to data from self
  resource/self-metrics:
    attributes:
      - key: "splashtop.datacenter"
        value: ${ecs_cluster_name}
        action: "insert"
      - key: "splashtop.region"
        value: ${ecs_region}
        action: "insert"

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  telemetry:
    metrics:
      address: ${env:HOSTNAME}:8888
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp/ecs-otel
      processors:
        - memory_limiter
        - resource
        - batch
      exporters: ParseJson(${env:otel_exporters_list})
    metrics:
      receivers:
        - otlp/ecs-otel
      processors:
        - memory_limiter
        - resource
        - batch
      exporters: ParseJson(${env:otel_exporters_list})
    metrics/self-metrics:
      receivers:
        - prometheus/ecs
      processors:
        - memory_limiter
        - resource
        - resource/self-metrics
        - batch
      exporters: ParseJson(${env:otel_exporters_list})
    logs:
      receivers:
        - otlp/ecs-otel
      processors:
        - memory_limiter
        - resource
        - batch
      exporters: ParseJson(${env:otel_exporters_list})