apiVersion: v2
name: stp-o11y
description: A Helm chart for stp-o11y tools
type: application
version: 1.1.4
appVersion: "0.0.0"
dependencies:
- name: kubernetes-event-exporter
  version: 2.15.2
  repository: "https://charts.bitnami.com/bitnami"
  condition: kubernetes-event-exporter.enabled
- name: prometheus-node-exporter
  version: 4.30.2
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: prometheus-node-exporter.enabled
- name: victoria-metrics-agent
  version: "0.9.11"
  repository: "https://victoriametrics.github.io/helm-charts/"
  condition: victoria-metrics-agent.enabled
- name: kube-state-metrics
  version: 3.14.2
  repository: "https://charts.bitnami.com/bitnami"
  condition: kube-state-metrics.enabled
- name: telegraf
  version: 1.8.53
  repository: "https://helm.influxdata.com/"
  condition: telegraf.enabled