# appNodeSelector: &appNodeSelector devops
eksClusterName: &eksClusterName local-cluster
vmProxyEndpoint: &vmProxyEndpoint ""
env:
  vault_addr: ""
  vault_sns_arn: ""
  vault_sns_subject: ""
  vault_sns_message: ""
  vault_check_period: "*/1 * * * *"

kubernetes-event-exporter:
  enabled: false
  fullnameOverride: "kubernetes-event-exporter"
  networkPolicy:
    enabled: false
  config:
    logLevel: debug
    metricsNamePrefix: "event_exporter_"
    logFormat: json
    receivers:
      # - name: dump
      #   file:
      #   layout: {}
      #   path: /dev/stdout
      - name: loki
        loki:
          streamLabels:
            app: kubernetes-event-exporter
            dataCenter: local-cluster
          url: http://loki:3100/loki/api/v1/push
          # layout:
          #   message: "{{ .Message }}"
          #   reason: "{{ .Reason }}"
          #   type: "{{ .Type }}"
          #   count: "{{ .Count }}"
          #   kind: "{{ .InvolvedObject.Kind }}"
          #   name: "{{ .InvolvedObject.Name }}"
          #   namespace: "{{ .Namespace }}"
          #   component: "{{ .Source.Component }}"
          #   host: "{{ .Source.Host }}"
      # - name: webhook
      # use lambda function Url
      # allow NONE auth type
      # webhook:
      # lambda python example see lambda/
      # headers:
      #   data-center: local-cluster
      # endpoint: https://xxxxxxxxxxxxx.lambda-url.region.on.aws/
    # route:
      # routes:
        # - match:
        #   - receiver: dump
        # - match:
        #     - receiver: loki
      # - match:
      # - receiver: webhook

kube-state-metrics:
  enabled: true
  fullnameOverride: "kube-state-metrics"
  networkPolicy:
    enabled: false
  # nodeSelector:
  #   app: *appNodeSelector

prometheus-node-exporter:
  enabled: true
  fullnameOverride: "node-exporter"
  networkPolicy:
    enabled: false
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9100"
      prometheus.io/path: "/metrics"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - arm64
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate


victoria-metrics-agent:
  fullnameOverride: "victoria-metrics-agent"
  enabled: true
  replicaCount: 1
  deployment:
    enabled: false
  statefulset:
    enabled: true
    clusterMode: true
    replicationFactor: 1
    updateStrategy:
      type: RollingUpdate
  # nodeSelector:
  #   app: *appNodeSelector
  config:
    global:
      scrape_interval: 30s
      external_labels:
        datacenter: *eksClusterName
    scrape_configs:
    - job_name: vmagent
      static_configs:
        - targets: ["%{HOSTNAME}:8429"]
    - job_name: "kubernetes-apiservers"
      kubernetes_sd_configs:
        - role: endpoints
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
        - source_labels:
            [
              __meta_kubernetes_namespace,
              __meta_kubernetes_service_name,
              __meta_kubernetes_endpoint_port_name,
            ]
          action: keep
          regex: default;kubernetes;https
    - job_name: "kubernetes-nodes"
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/$1/proxy/metrics
    - job_name: "kubernetes-nodes-cadvisor"
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      honor_timestamps: false
    - job_name: "kubernetes-service-endpoints"
      kubernetes_sd_configs:
        - role: endpointslices
      relabel_configs:
        - action: drop
          source_labels: [__meta_kubernetes_pod_container_init]
          regex: true
        - action: keep_if_equal
          source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels:
            [
              __address__,
              __meta_kubernetes_service_annotation_prometheus_io_port,
            ]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
        - source_labels: [__meta_kubernetes_service_name]
          target_label: job
          replacement: ${1}
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: node
    - job_name: "kubernetes-service-endpoints-slow"
      scrape_interval: 5m
      scrape_timeout: 30s
      kubernetes_sd_configs:
        - role: endpointslices
      relabel_configs:
        - action: drop
          source_labels: [__meta_kubernetes_pod_container_init]
          regex: true
        - action: keep_if_equal
          source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
          action: keep
          regex: true
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels:
            [
              __address__,
              __meta_kubernetes_service_annotation_prometheus_io_port,
            ]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
        - source_labels: [__meta_kubernetes_service_name]
          target_label: job
          replacement: ${1}
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: node
    - job_name: "kubernetes-services"
      metrics_path: /probe
      params:
        module: [http_2xx]
      kubernetes_sd_configs:
        - role: service
      relabel_configs:
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_probe]
          action: keep
          regex: true
        - source_labels: [__address__]
          target_label: __param_target
        - target_label: __address__
          replacement: blackbox
        - source_labels: [__param_target]
          target_label: instance
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
    - job_name: "kubernetes-pods"
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - action: drop
          source_labels: [__meta_kubernetes_pod_container_init]
          regex: true
        - action: keep_if_equal
          source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels:
            [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: node
  remoteWriteUrls:
    # send data to victoria-metrics-cluster-vminsert in the same cluster.
    - http://victoria-metrics-cluster-vminsert.default:8480/insert/0/prometheus
    # send data to remoteWrite 
    # - http://remote-write-url:8428/api/v1/write

vault_health_check:
  enabled: false

telegraf:
  fullnameOverride: "telegraf"
  enabled: false
  replicaCount: 1
  image:
    repo: "public.ecr.aws/docker/library/telegraf"
    tag: "1.30.3-alpine"
    pullPolicy: IfNotPresent
  env:
    - name: HOSTNAME
      value: "telegraf-polling-service"
  resources: 
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
  nodeSelector:
    app: devops
  service:
    enabled: false
  rbac:
    create: true
  pdb:
    create: false
  config:
    agent:
      interval: "5s"
      round_interval: true
      metric_batch_size: 1000
      metric_buffer_limit: 10000
      collection_jitter: "0s"
      flush_interval: "5s"
      flush_jitter: "0s"
      precision: ""
      debug: false
      quiet: false
      logfile: ""
      hostname: "$HOSTNAME"
      omit_hostname: false
    outputs:
      - http:
          url: "https://vm-insert.example.com/insert/0/prometheus"
          data_format: "prometheusremotewrite"
  
          headers: 
            Content-Type: "application/x-protobuf"
            Content-Encoding: "snappy"
            X-Prometheus-Remote-Write-Version: "0.1.0"
            
    inputs:
      - dns_query:
          servers:
            - "kube-dns.kube-system.svc.cluster.local."
          timeout: "4s"
          domains:
            - "kubernetes.default.svc.cluster.local"
            - "www.google.com"
            - "uber.com"
          tags:
            datacenter: "local-cluster"
  metrics:
    create: true
    health:
      enabled: true
      service_address: "http://:8888"
      threshold: 5000.0

mtail:
  enabled: true
  image:
    repository: ghcr.io/google/mtail
    tag: 3.0.8
  resources: {}
  tolerations:
  - operator: Exists
    effect: NoSchedule
  nodeSelector:
    kubernetes.io/os: linux
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
                - arm64
            - key: eks.amazonaws.com/compute-type
              operator: NotIn
              values:
              - fargate
  containerLogs: []
  # <pod-name>_<namespace>_<container-name>-<container-id>.log
  # - ".*.log"
  progs:
    nginx: |-
    