# Version: v2-0
# Description: 
#   - Remove `match_once: true` from routing pipelines (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/routingconnector/README.md#match_once)
#   - fix format of telemetry metrics
# Compatible with: v1-0

receivers:
  otlp/ecs-otel:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus/ecs:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector-trace
        scrape_interval: 10s
        static_configs:
          - targets:
              - ${env:HOSTNAME}:8888

exporters:
  debug:
    verbosity: ${env:otel_conf_debug_verbosity}
  otlphttp/cent-monitor:
    endpoint: "https://cent-otel.ops.splashtop.com:443"
  otlphttp/tperd-monitor:
    endpoint: "https://cent-otel-devops.ops.tperd.splashtop.eu:443"

processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
      - key: "splashtop.env"
        value: ${env:splashtop_env}
        action: "insert"
      - key: "splashtop.stack"
        value: ${env:splashtop_stack}
        action: "insert"
  # add attribute to data from self
  resource/self-metrics:
    attributes:
      - key: "splashtop.datacenter"
        value: ${env:ecs_cluster_name}
        action: "insert"
      - key: "splashtop.region"
        value: ${env:ecs_region}
        action: "insert"
  tail_sampling:
    # The quantities of decision_wait and num_traces will affect memory usage; therefore, after adjustment, it is necessary to ensure sufficient memory is available.
    decision_wait: 5s # The time to decide. has to be more than the latency policy’s threshold_ms.
    num_traces: 450000 # The amount of traces handled, if it goes over this, gets dumped.
    expected_new_traces_per_sec: 20000 # The amount of traces expected per second.
    policies:
      [
        {
          name: "error-policy",
          type: "status_code",
          status_code: { status_codes: ["ERROR"] }
        },
        {
          name: "latency-policy",
          type: "latency",
          latency: { threshold_ms: 3000 }
        },
        {
          name: "default-policy",
          type: "probabilistic",
          probabilistic: { sampling_percentage: 10 }
        }
      ]

connectors:
  # routing rules: 
  # 1. DEV -> tperd-monitor & cent-monitor (for load testing)
  # 2. PROD-OC & QA-EU -> both tperd-monitor & cent-monitor
  # 3. OTHERS -> cent-monitor
  routing/traces:
    error_mode: ignore
    table:
      - context: span
        statement: route() where IsMatch(resource.attributes["splashtop.env"], "PROD") and IsMatch(resource.attributes["splashtop.stack"], "OC")
        pipelines: [traces/multi-exporters]
      - context: span
        statement: route() where IsMatch(resource.attributes["splashtop.env"], "QA") and IsMatch(resource.attributes["splashtop.stack"], "EU")
        pipelines: [traces/multi-exporters]
      - context: span
        statement: route() where IsMatch(resource.attributes["splashtop.env"], "DEV")
        pipelines: [traces/multi-exporters]
      - context: span
        statement: route()
        pipelines: [traces/cent-monitor]
  routing/metrics:
    error_mode: ignore
    table:
      - context: metric
        statement: route() where IsMatch(resource.attributes["splashtop.env"], "PROD") and IsMatch(resource.attributes["splashtop.stack"], "OC")
        pipelines: [metrics/multi-exporters]
      - context: metric
        statement: route() where IsMatch(resource.attributes["splashtop.env"], "QA") and IsMatch(resource.attributes["splashtop.stack"], "EU")
        pipelines: [metrics/multi-exporters]
      - context: metric
        statement: route() where IsMatch(resource.attributes["splashtop.env"], "DEV")
        pipelines: [metrics/multi-exporters]
      - context: metric
        statement: route()
        pipelines: [metrics/cent-monitor]
extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: ${env:HOSTNAME}
                port: 8888
  extensions:
    - health_check
  pipelines:
    traces:
      receivers: [otlp/ecs-otel]
      processors: [memory_limiter, batch, tail_sampling]
      exporters: [routing/traces]
    traces/tperd-monitor:
      receivers: [routing/traces]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/tperd-monitor, debug]
    traces/cent-monitor:
      receivers: [routing/traces]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/cent-monitor, debug]
    traces/multi-exporters:
      receivers: [routing/traces]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/cent-monitor, otlphttp/tperd-monitor, debug]
    metrics:
      receivers: [otlp/ecs-otel]
      processors: [memory_limiter, batch]
      exporters: [routing/metrics]
    metrics/self-metrics:
      receivers: [prometheus/ecs]
      processors: [memory_limiter, resource, resource/self-metrics, batch]
      exporters: [routing/metrics]
    metrics/tperd-monitor:
      receivers: [routing/metrics]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/tperd-monitor, debug]
    metrics/cent-monitor:
      receivers: [routing/metrics]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/cent-monitor, debug]
    metrics/multi-exporters:
      receivers: [routing/metrics]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/cent-monitor, otlphttp/tperd-monitor, debug]
