{{- if .Values.vmproxy.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-k8s
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - ingresses
  - configmaps
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics","/metrics/resources"]
  verbs: ["get"]
- apiGroups:
    - route.openshift.io
    - image.openshift.io
  resources:
    - routers/metrics
    - registry/metrics
  verbs:
    - get
{{- end }}