name: always-run-check

on:
  pull_request:
    paths:
      - '*/**/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo "Check ... always-run-check ✅"